version: '3.7'
services:
  terraform:
    image: hashicorp/terraform
    volumes:
      - ./terraform:/terra
    working_dir: /terra
    environment:
      - ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID} #azure_subscription_id
      - ARM_TENANT_ID=${ARM_TENANT_ID} #azure_subscription_tenant_id
      - ARM_CLIENT_ID=${ARM_CLIENT_ID} #service_principal_appid
      - ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET} #service_principal_password
  selenium: #SELENIUM
    image: selenium/standalone-chrome-debug  
    ports:
      - 4444:4444
      - 5901:5900
  website:  #WEBSITE
    build: 
      context: .
    ports:
      - 80:80
  unit-tests: # RSpec testing
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    build: 
      context: .
      dockerfile: rspec.dockerfile
    volumes:
      - ".:/app"
    command: 
      - --pattern
      - /app/spec/unit/*_spec.rb
  #database:
  #application_server: