version: '3.7'
services:
  jenkins:  # JENKINS
    build: 
      context: .
      dockerfile: jenkins.dockerfile
    volumes:
      - C:\jenkins_home:/var/jenkins_home
      - ".:/app"
    ports:
      - 8080:8080
      - 50000:50000 # Master - slave communication
  azure:  # AZURE
    image: mcr.microsoft.com/azure-cli
  terraform:
    image: hashicorp/terraform
    volumes:
      - ./terraform:/terra
    working_dir: /terra
    env_file:
      - azure.env
  selenium: #SELENIUM
    image: selenium/standalone-chrome-debug  
    ports:
      - 4444:4444
      - 5901:5900
  website:  #WEBSITE
    build: 
      context: .
    ports:
      - 80:80
  integration-tests: # RSpec testing
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    build: 
      context: .
      dockerfile: rspec.dockerfile
    volumes:
      - ".:/app"
    command: 
      - --pattern
      - /app/spec/integration/*_spec.rb
  unit-tests: # RSpec testing
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    build: 
      context: .
      dockerfile: rspec.dockerfile
    volumes:
      - ".:/app"
    command: 
      - --pattern
      - /app/spec/unit/*_spec.rb
  #database:
  #application_server: